stages:
  - deploy

pages:
  stage: deploy
  image: $CI_REGISTRY/raphael.dutrieux/fordead_package
  script:
    - conda init bash
    - conda activate fordead
    - python -V  # Print out python version for debugging
    - pip install portray python-markdown-math
    - pip install -e .
    - portray as_html -c pyproject.toml
    - mv site public
  artifacts:
    paths:
     - public
  only:
   - master
   - schedules
