.shared_windows_runners:
  tags:
  - win10-mop8243
  # - shared-windows
  # - windows
  # - windows-1809
stages:
  - build
  - deploy
## docker build does not end within the 1h limit
## thus it was build locally and transfered manually
#docker-ci:
#  stage: deploy
#  image: docker:19.03.8
#  services:
#    - docker:19.03.8-dind
#  script:
#    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
#    - export VERSION=`grep __version__ fordead/_version.py| sed -E 's/.*([0-9]+\.[0-9]+\.[0-9]+).*/\1/'`
#    - echo $CI_REGISTRY_IMAGE
#    - echo $VERSION
#    - docker pull $CI_REGISTRY_IMAGE:latest || true
#    - docker build --cache-from $CI_REGISTRY_IMAGE:latest -t $CI_REGISTRY_IMAGE:$VERSION .
#    - docker push $CI_REGISTRY_IMAGE:$VERSION
#  only:
#    - docker_ci

intall-win:
  stage: build
  extends:
    - .shared_windows_runners
  variables: 
    ErrorActionPreference: stop 
  script:
    - git config --system core.longpaths true
    # install Miniforge if $env:userprofile\miniforge3 is not found
    # other just load profile
    - gitlab-ci\conda-build.ps1
    - mamba env create -y -n fordead-gitlab-ci -f environment.yml
    - cd docs\examples
    - conda run -n fordead-gitlab-ci --live-stream python download_data.py
    - conda run -n fordead-gitlab-ci --live-stream python full_test_script.py
    # cleaning
    - Remove-Item2 -Recurse fordead_data
    - Remove-Item2 -Recurse test_output_dir
    - mamba remove -n fordead-gitlab-ci --all -y
    - mamba clean --all -y
  only:
    - merge_requests
    - schedules
  

install-linux:
  stage: build
  image: mambaorg/micromamba
  variables:
    MAMBA_DOCKERFILE_ACTIVATE: 1
  script:
    - micromamba install -y -n base -f environment.yml
    - pip install -e .
    - python -c "import fordead"
    - cd docs/examples
    - python download_data.py
    - python full_test_script.py
  only:
    - dev
    - master

#[![version](https://img.shields.io/badge/dynamic/json.svg?label=version&url=https://gitlab.com/fordead/fordead_package/-/jobs/artifacts/master/raw/badges.json?job=badges&query=version&colorB=blue)](https://gitlab.com/fordead/fordead_package)
badges:
  stage: deploy
  image: python:latest
  script:
    - version=`grep __version__ fordead/_version.py| sed -E 's/.*([0-9]+\.[0-9]+\.[0-9]+).*/\1/'`
    - echo "{\"version\":\"$version\"}" > badges.json
  artifacts:
    paths:
      - badges.json
  only:
    - master


pages:
  stage: deploy
  image: $CI_REGISTRY/fordead/fordead_package:latest
  script:
    - conda env list
    - pip install portray python-markdown-math mdx-breakless-lists mkdocs-click
    - python -V  # Print out python version for debugging
    - pip install -e .
    - portray as_html -c pyproject_doc.toml
    - mv site public
  artifacts:
    paths:
     - public
  only:
   - master
   - pages
