name: fordead_env
channels:
  - conda-forge
dependencies:
  - python>=3.7
  - numpy
  - fiona = 1.8.17
  - geopandas
  - rasterio
  - xarray
  - scipy
  - dask
  - pathlib
  - rioxarray
  - path
  - plotly

