name: fordead
channels:
  - conda-forge
  - nodefaults
dependencies:

  - mkdocs
  - mkdocs-click
  - mkdocs-material
  - mdx_truly_sane_lists
  - portray
  - python-markdown-math
  - pip:
    - mdx-breakless-lists
    

