name: fordead_env
channels:
  - conda-forge
dependencies:
  - python=3.8.2
  - numpy = 1.21.4
  - fiona=1.8.20
  - geopandas=0.10.2
  - rasterio=1.2.10
  - xarray=0.20.1
  - scipy=1.7.2
  - dask=2021.11.2
  - pathlib=1.0.1
  - path=16.2.0
  - plotly=5.4.0
  - netcdf4=1.5.8
  - matplotlib=3.5.0
  - rioxarray=0.8.0