name: fordead_env
channels:
  - conda-forge
dependencies:
  - python = 3.9.0
  - numpy
  - fiona
  - geopandas
  - rasterio
  - xarray
  - scipy
  - dask
  - pathlib
  - rioxarray
  - path
  - plotly = 5.9.0
  - netcdf4
  - matplotlib
  - pip:
    - git+https://gitlab.com/fordead/fordead_package.git
