name: fordead_env
channels:
  - conda-forge
dependencies:
  - python = 3.9.0
  - numpy <= 1.23
  - fiona <= 1.8.21
  - geopandas <= 0.11.0
  - rasterio <= 1.3.0
  - xarray <= 2022.3.0
  - scipy <= 1.8.1
  - dask <= 2022.6.1
  - pathlib
  - rioxarray <= 0.11.1
  - path
  - plotly = 5.9.0
  - netcdf4 <= 4.8.1
  - matplotlib
  - pip:
    - pystac
    - pystac_client
    - planetary_computer
    - git+https://gitlab.com/fordead/fordead_package.git
