name: fordead_env
channels:
  - conda-forge
dependencies:
  - python = 3.9.0
  - numpy
  - fiona
  - geopandas = 0.11.0
  - rasterio = 1.3.0
  - xarray = 2022.3.0
  - scipy
  - dask
  - pathlib
  - rioxarray
  - path
  - plotly
  - netcdf4
  - matplotlib
