name: fordead
channels:
  - conda-forge
  - nodefaults
dependencies:
  - click
  - click-option-group
  - dask
  # - eodag # waiting for release, see 
  - shapely >= 2.0.0
  - fiona
  - geopandas
  - git
  - matplotlib
  - numpy < 2
  - path
  - pathlib
  - pip
  - planetary-computer
  - plotly
  - python
  - pystac
  - rasterio
  - rioxarray
  - scipy
  - stackstac
  - xarray
  - jsonschema
  - referencing

  # additionnal dependencies for stac-static
  - pygeofilter
  - pyarrow != 15.0.2
  - pip:
    # ensure that stac-geoparquet v0.3.2+ (conda version is too old),
    # dependency of stac-static
    - stac-geoparquet>=0.3.2
    - git+https://github.com/jsignell/stac-static
    - git+https://gitlab.com/fordead/fordead_package
    - git+https://github.com/CS-SI/eodag.git@develop


