name: fordead_env
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - fiona
  - geopandas
  - rasterio
  - xarray
  - scipy
  - dask
  - pathlib
  - rioxarray
  - path
  - plotly
  - netcdf4
  - matplotlib
