name: fordead_env
channels:
  - conda-forge
dependencies:
  - python=3.8.2
  - numpy
  - fiona
  - geopandas = 0.9.0
  - rasterio
  - xarray
  - scipy
  - dask
  - pathlib
  - rioxarray
  - path
  - plotly
  - netcdf4
  - matplotlib
