# test website locally:
# portray in_browser -c pyproject.toml
# generate website with the following:
# portray as_html -c pyproject.toml

# Current pypoject.toml seems to make error with `pip install .`,
# due to extra_markdown_extensions that is a list of values and tables...
# And inline mixed array/table does not seem to work in portray...
# Example (not working): extra_markdown_extensions = ['mdx_breakless_lists', 'mkdocs-click', mdx_math = {enable_dollar_delimiter = 1}]
# The solution was to rename pyproject.toml to pyproject_doc.toml

[tool.portray]
#    docs_dir = "docs"
# output_dir = "site"
#    modules = ["fordead"]
    modules = ["fordead.decline_detection", "fordead.ImportData", "fordead.masking_vi", "fordead.maja_fun", "fordead.ModelVegetationIndex", "fordead.writing_data"]
    extra_markdown_extensions = ['mdx_breakless_lists', 'mkdocs-click']

[[tool.portray.extra_markdown_extensions]]
    [tool.portray.extra_markdown_extensions.mdx_math]
        enable_dollar_delimiter = True
        use_gitlab_delimiters=True
[[tool.portray.extra_markdown_extensions]]
    [tool.portray.extra_markdown_extensions.toc]
        toc_depth = 5
        # toc_depth = "2-5" # for bootstrap


[tool.portray.pdocs]
# name = "API"
exclude_source = 1
template_dir = "templates/pdocs"

[tool.portray.mkdocs]
    site_name = "fordead"
    extra_css = ['docs/style.css', 'examples/style.css']
    edit_uri = '-/edit/master/'

    extra_javascript = ['https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS_HTML']
#    extra_javascript = ['docs/menu.js']
#     [tool.portray.mkdocs.theme]
#         name = "bootstrap"

[tool.portray.mkdocs.theme]
name = "material"
palette = {primary = "blue grey", accent = "pink"}

[tool.portray.mkdocs.theme.icon]
repo='fontawesome/brands/gitlab'


