# test website locally:
# portray in_browser -c pyproject.toml
# generate website with the following:
# portray as_html -c pyproject.toml

# Current pypoject.toml seems to make error with `pip install .`,
# due to extra_markdown_extensions that is a list of values and tables...
# And inline mixed array/table does not seem to work in portray...
# Example (not working): extra_markdown_extensions = ['mdx_breakless_lists', 'mkdocs-click', mdx_math = {enable_dollar_delimiter = 1}]
# The solution was to rename pyproject.toml to pyproject_doc.toml

[tool.portray]
#    docs_dir = "docs"
# output_dir = "site"
#    modules = ["fordead"]
    modules = ["fordead.dieback_detection", "fordead.import_data", "fordead.masking_vi", "fordead.maja_fun", "fordead.model_vegetation_index", "fordead.writing_data", "fordead.validation_module"]
    extra_markdown_extensions = ['mdx_breakless_lists', 'mkdocs-click']

[[tool.portray.extra_markdown_extensions]]
    [tool.portray.extra_markdown_extensions.mdx_math]
        enable_dollar_delimiter = 1
        use_gitlab_delimiters = 1
[[tool.portray.extra_markdown_extensions]]
    [tool.portray.extra_markdown_extensions.toc]
        toc_depth = 5
        # toc_depth = "2-5" # for bootstrap


[tool.portray.pdocs]
# name = "API"
exclude_source = 1
template_dir = "templates/pdocs"

[tool.portray.mkdocs]
    site_name = "fordead"
    extra_css = ['docs/style.css']
    edit_uri = '-/edit/master/'

    extra_javascript = ['https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS_HTML']
#    extra_javascript = ['docs/menu.js']
#     [tool.portray.mkdocs.theme]
#         name = "bootstrap"

[tool.portray.mkdocs.theme]
name = "material"
palette = {primary = "blue grey", accent = "pink"}

[tool.portray.mkdocs.theme.icon]
repo='fontawesome/brands/gitlab'


[[tool.portray.mkdocs.nav]]
Home = "README.md"
[[tool.portray.mkdocs.nav]]
Installation = "docs/Installation.md"

[[tool.portray.mkdocs.nav]]
	[[tool.portray.mkdocs.nav.Tutorials]]
			[[tool.portray.mkdocs.nav.Tutorials.Dieback_Detection]]
			"Introduction" = "docs/Tutorials/Dieback_Detection/00_Intro.md"
			[[tool.portray.mkdocs.nav.Tutorials.Dieback_Detection]]
			"Step 1. Compute masked vegetation index" = "docs/Tutorials/Dieback_Detection/01_compute_masked_vegetationindex.md"
			[[tool.portray.mkdocs.nav.Tutorials.Dieback_Detection]]
			"Step 2. Train model" = "docs/Tutorials/Dieback_Detection/02_train_model.md"
			[[tool.portray.mkdocs.nav.Tutorials.Dieback_Detection]]
			"Step 3. Dieback detection" = "docs/Tutorials/Dieback_Detection/03_dieback_detection.md"
			[[tool.portray.mkdocs.nav.Tutorials.Dieback_Detection]]
			"Step 4. Compute forest mask" = "docs/Tutorials/Dieback_Detection/04_compute_forest_mask.md"
			[[tool.portray.mkdocs.nav.Tutorials.Dieback_Detection]]
			"Step 5. Export results" = "docs/Tutorials/Dieback_Detection/05_export_results.md"
			[[tool.portray.mkdocs.nav.Tutorials.Dieback_Detection]]
			"Creating a timelapse" = "docs/Tutorials/Dieback_Detection/06_create_timelapse.md"
			[[tool.portray.mkdocs.nav.Tutorials.Dieback_Detection]]
			"Creating graphs" = "docs/Tutorials/Dieback_Detection/07_create_graphs.md"
			[[tool.portray.mkdocs.nav.Tutorials.Dieback_Detection]]
			"Updating detection" = "docs/Tutorials/Dieback_Detection/08_updating_detection.md"
	[[tool.portray.mkdocs.nav.Tutorials]]
			[[tool.portray.mkdocs.nav.Tutorials.Validation]]
			"Introduction" = "docs/Tutorials/Validation/00_Intro.md"

	
[[tool.portray.mkdocs.nav]]
    [[tool.portray.mkdocs.nav."User guides".English]]
    "1. Compute masked vegetation index" = "docs/user_guides/english/01_compute_masked_vegetationindex.md"
    [[tool.portray.mkdocs.nav."User guides".English]]
    "2. Train model" = "docs/user_guides/english/02_train_model.md"
    [[tool.portray.mkdocs.nav."User guides".English]]
    "3. Dieback detection" = "docs/user_guides/english/03_dieback_detection.md"    
	[[tool.portray.mkdocs.nav."User guides".English]]
    "4. Compute forest mask" = "docs/user_guides/english/04_compute_forest_mask.md"    
	[[tool.portray.mkdocs.nav."User guides".English]]
    "5. Export results" = "docs/user_guides/english/05_export_results.md"
	[[tool.portray.mkdocs.nav."User guides".English]]
    "Visualisation tools" = "docs/user_guides/english/Results_visualisation.md"
	
	[[tool.portray.mkdocs.nav."User guides".English]]
		[[tool.portray.mkdocs.nav."User guides".English."Other tools"]]
		"Computing vegetation index" = "docs/user_guides/english/other_tools/ex_computing_vegetation_index.md"
		[[tool.portray.mkdocs.nav."User guides".English."Other tools"]]
		"Using TileInfo object" = "docs/user_guides/english/other_tools/ex_tileinfo_object.md"
		[[tool.portray.mkdocs.nav."User guides".English."Other tools"]]
		"Downloading and preprocessing Sentinel-2 data from THEIA" = "docs/user_guides/english/other_tools/theia_preprocess.md"
		
    [[tool.portray.mkdocs.nav."User guides".'Français']]
    "1. Calcul de l'indice de végétation et des masques" = "docs/user_guides/french/01_compute_masked_vegetationindex.md"
    [[tool.portray.mkdocs.nav."User guides".'Français']]
    "2. Apprentissage du modèle" = "docs/user_guides/french/02_train_model.md"
    [[tool.portray.mkdocs.nav."User guides".'Français']]
    "3. Détection du dépérissement" = "docs/user_guides/french/03_dieback_detection.md"    
	[[tool.portray.mkdocs.nav."User guides".'Français']]
    "4. Calcul du masque forêt" = "docs/user_guides/french/04_compute_forest_mask.md"    
	[[tool.portray.mkdocs.nav."User guides".'Français']]
    "5. Export des résultats" = "docs/user_guides/french/05_export_results.md"
	[[tool.portray.mkdocs.nav."User guides".'Français']]
    "Outils de visualisation" = "docs/user_guides/french/Results_visualisation.md"
	

	
[[tool.portray.mkdocs.nav]]
"Command line" = "docs/cli.md"